### ISSUE TITLE
Login Error After Upgrade from 0.9.1 to 0.9.2

### ISSUE THREAD

**Issue by adhami03** [timescale/timescaledb#543]
After timescaledb upgraded to 0.9.2 on my Ubuntu 16.04 servers through apt, I can no longer log into the databases with timescale setup.  When I use pgAdmin 4, I get the following message: "ERROR: could not access file "timescaledb-0.9.1": No such file or directory".  The only way I have been able to get around this is to disable the timescaledb library in the postgresql.conf file and restart the server.

**Comment by solugebefola** [comment]
Did you get a typical response from the `ALTER EXTENSION timescaledb UPDATE;` command?

**Comment by adhami03** [comment]
I was not aware that command had to be run manually since I installed timescale via ppa. Since updates are installed automatically, what's the recommendation to prevent login errors like this?  Is the only option to install from source?

**Comment by RobAtticus** [comment]
For now you will probably want to connect directly using `psql -X` to run the update. We may have to consider how to handle this more seamlessly on our end with regard to pgAdmin and similar setups.

**Comment by RobAtticus** [comment]
@AndyMender Yeah, as you mentioned there are problems with that approach. We'd also need input to know which databases use TimescaleDB. We'll definitely keep thinking about it though.

**Comment by magnusnissel** [comment]
Unfortunately I face the same issue, but I am also now unable to access psql / connect to postgres in any way. Is there any way to fix this via configuration files or manually downgrade back to the old version of timescaledb?

**Comment by ashern** [comment]
Quick bump.

The workaround is simple, but this behavior is surprising for anyone installing from ppa. I would recommend at least putting a warning in the install section of the docs that package manager upgrades require this additional manual step, which isn't immediately obvious.

**Comment by RobAtticus** [comment]
Thanks @ashern , we'll keep that in mind as we look for ways to make this process more streamline.

**Comment by boromisp** [comment]
Just an other bump, with an anecdote, upgrading from 0.9.2 to 0.11.0, on Ubuntu 16.04, ppa:

The changes introduced in https://github.com/timescale/timescaledb/commit/37142e9094dd25e0b3818cb1197900bd16e02185 blocked the `UPDATE EXTENSION`, and I could not execute the commands suggested at https://github.com/timescale/timescaledb/blob/148f2da9248289ed396337e32b31998b5fcdd266/src/hypertable.c#L1162, because the 0.9.2 lib had been removed by the update.
I've tried to build the 0.9.2 version from source, but got something like `conflicting types for ‘PGSemaphoreData’`, so I've eventually ended up downloading the missing lib from a redhat repository.

Would it be possible to keep the previous libs around even after updating the package?

**Comment by RobAtticus** [comment]
Hi @boromisp , we've seen this a few times and so far our builder/host for the PPA does not support keeping older versions of the deb around. However, it does seem strange to me that the old lib/.so was removed when you updated. There shouldn't be anything in the update script to remove old files.

**Comment by dianasaur323** [comment]
Hmm... I'm actually pretty sure we fixed this since we add more version in our PPA now.. Going to close out, but @RobAtticus re-open if I'm wrong?

**Comment by RobAtticus** [comment]
Yes, turns out old versions removed the old .so/.sql files causing this issue. Now that we include multiple versions in the latest, it should be resolved.

**Comment by waterdrop01** [comment]
Hi @RobAtticus , would that be related to my issue? https://github.com/timescale/timescaledb/issues/1425
